### ISSUE TITLE
JS error without passing options

### ISSUE THREAD

**Issue by dhqvinh** [anteriovieira/vue-cast-props#1]
From the document, to use vue-cast-props:
```
import VueCastProps from 'vue-cast-props'

Vue.use(VueCastProps, /* options */)
```
It's not clear what should be passed into the options param, so I've tried thesse values:
1. Vue.use(VueCastProps) -> Error: index.js:12 Uncaught TypeError: Cannot read property 'casts' of undefined
2. Vue.use(VueCastProps, {}) -> Error: Util.js:9 Uncaught TypeError: Cannot convert undefined or null to object
3. Vue.use(VueCastProps, {casts: {}}) -> This is fine

Please make it work out of the box without passing any options, or update the guideline in the README file.
Thanks.

**Comment by anteriovieira** [comment]
Thanks @dhqvinh , try `v0.0.4`
